// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCW2_4CWz4GP_Ivo1nxLZSmgLsRiJuYkU',
    appId: '1:1055753826989:web:b8ec675d8fb24b9113cc24',
    messagingSenderId: '1055753826989',
    projectId: 'chat-app-a725a',
    authDomain: 'chat-app-a725a.firebaseapp.com',
    storageBucket: 'chat-app-a725a.appspot.com',
    measurementId: 'G-TJS4M48768',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbJCSiF9XKO76-pzS_r3d9c3rmpEfDTa4',
    appId: '1:1055753826989:android:216fc09670da973013cc24',
    messagingSenderId: '1055753826989',
    projectId: 'chat-app-a725a',
    storageBucket: 'chat-app-a725a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBja9cPBKUiiVpXdJ0kZSS1XcMjX3iySN4',
    appId: '1:1055753826989:ios:aa57aa306e75210613cc24',
    messagingSenderId: '1055753826989',
    projectId: 'chat-app-a725a',
    storageBucket: 'chat-app-a725a.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBja9cPBKUiiVpXdJ0kZSS1XcMjX3iySN4',
    appId: '1:1055753826989:ios:aa57aa306e75210613cc24',
    messagingSenderId: '1055753826989',
    projectId: 'chat-app-a725a',
    storageBucket: 'chat-app-a725a.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCW2_4CWz4GP_Ivo1nxLZSmgLsRiJuYkU',
    appId: '1:1055753826989:web:d871a063e71b93f413cc24',
    messagingSenderId: '1055753826989',
    projectId: 'chat-app-a725a',
    authDomain: 'chat-app-a725a.firebaseapp.com',
    storageBucket: 'chat-app-a725a.appspot.com',
    measurementId: 'G-N12VF9K32J',
  );

}